services:
  quartz:
    build: .
    command: npx quartz build --serve
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - ${HOST_PORT:-8080}:8080
    volumes:
      - .:/app
      - /app/node_modules
