services:
  quartz:
    build: .
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./content:/app/content
      - ./public:/app/public
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./public:/config/www
    ports:
      - ${HOST_PORT:-8080}:80
